### ISSUE TITLE
HTU21D example does not work in release mode

### ISSUE THREAD

**Issue by forGGe** [forGGe/theCore#256]
See analyser output:

![2017-05-13-003054_933x138_scrot](https://cloud.githubusercontent.com/assets/5261821/26050309/cbfe03ae-3966-11e7-9706-4141e36303da.png)

**Comment by rasendubi** [comment]
I'll decipher what happens:
- The first two types issue a soft reset command, so device goes down.
- The third and last byte is a start of a temperature read command.

It fails because the device did not answer with an ACK (due to it being resetting). Now the I2C driver is waiting for a Master Transmitter Mode Selected event, which never occurs due to the error.

This issue directly relates to #19. I would say, this issue is an instance of absent error handling.

A fast workaround is to add a ~15ms delay to allow HTU21D complete reset before issuing the read command.

**Comment by forGGe** [comment]
> A fast workaround is to add a ~15ms delay to allow HTU21D complete reset before issuing the read command.

@Dubland, since you are working on #183 , it will be useful to you also check @rasendubi's workaround.

**Comment by rasendubi** [comment]
ping @Dubland ?

**Comment by Dubland** [comment]
With delay after soft reset example working fine. Shall I create PR for adding the delay?

**Comment by rasendubi** [comment]
> Shall I create PR for adding the delay?

Yes please.

**Comment by forGGe** [comment]
@Dubland now, when #271 is merged, I propose to try find real root cause and fix it. @rasendubi can guide you trough it.

**Comment by forGGe** [comment]
@Dubland any news?

**Comment by forGGe** [comment]
Implement in #279 Thanks to @Dubland !
